[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kolide/osquery-go"

[[override]]
  name = "git.apache.org/thrift.git"
  revision = "0dd823580c78a79ae9696eb9b3650e400fff140f"
